Algoritmo "troca de numeros"

Var
a : inteiro
b : inteiro
troca : inteiro
Inicio
  escreval ("digite um numero")
  leia (a)
  escreval ("digite outro numero")
  leia (b)
  escreval ("valores originais")
  escreval("valor a " , a)
  escreval("valor b " , b)
  
  troca<- a
  a<- b
  b<- troca
  escreval("valores invertidos")
  escreval("valor a" , a)
  escreval("valor b" , b)
  
  
Fimalgoritmo