num1 = int(input("digite um numero "))
num2 = int(input("digte mais um numero "))
print("a soma entre os numeros é",num1 + num2)
print("a subtração entre os numeros é",num1 - num2)
print("a multiplicaçao entre os numeros é",num1 * num2)
print("a divisão entre os numeros é",num1 / num2)
